version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

  fast_api_app:
    build: 
      context: ./fast_api_app
    tty: true
    ports: 
      - '80:80'
    volumes:
      - model_data:/home/fast_api_app/model
      - ./fast_api_app:/home/fast_api_app
    env_file:
      - ./fast_api_app/env/.env
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app_network

  flask_service:
    build:
      context: ./frontend
    ports:
      - '5000:5000'
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/env/.env
    depends_on:
      - fast_api_app
    networks:
      - app_network


volumes:
  model_data:

networks:
  app_network:
    driver: bridge

