default_prompt: "invert the colors"
default_wrong_image_query: b'1234'
fast_api_handler_config:
  max_width: 1024
  max_height: 1024
  model_checkpoint: "timbrooks/instruct-pix2pix"
  num_inference_steps: 10
  image_guidance_scale: 1
  device: "cuda"